### ISSUE TITLE
Problems Checklist

### ISSUE THREAD

**Issue by Shushman** [sisl/MultiAgentAllocationTransit.jl#1]
- [x] Currently using half the max distance, and doing two shortest paths. Is that okay?
- [ ] Need to integrate with a rolling-horizon GTFS feed
- [x] Not using `depot_to_sites_dists`
- [ ] Using `JuMP v0.21` and up breaks task allocation (the `*` operator - see https://github.com/JuliaOpt/JuMP.jl/issues/2005)

**Comment by linzgood** [comment]
linux 16.04 or windows10 can run your code？

**Comment by Shushman** [comment]
I believe the early version was done on Ubuntu 16.04 before I upgraded my desktop; there should be no reason it does not work on 16.04 as long as the correct Julia dependencies are installed. I would imagine the same is true for Windows, though I have never tried it.
